# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: 1.20.0
repos:
-   repo: git@github.adtran.com:DeveloperExperience/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
    -   id: check-added-large-files
